imports = { 
   ansicolors = ".",
   underscore = ".", 
   base64 = ".",
   log = ".",
}

ansicolors = {
    url = "https://github.com/kikito/ansicolors.lua",
    pluck = "ansicolors.lua",
}

underscore = {
    url = "https://github.com/mirven/underscore.lua",
    export = "lib",
}

base64 = {
    url = "https://github.com/foundpatterns/lua-base64",
    pluck = "base64.lua",
}

log = {
    url = "https://github.com/foundpatterns/log.lua",
    pluck = "log.lua",
}

